/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JMenuItem;

//import org.jfree.chart.JFreeChart;
//import org.jfree.ui.RefineryUtilities;

import javax.swing.JOptionPane;
import javax.swing.ListModel;

import org.jfree.ui.RefineryUtilities;

import background.Dorm;
import background.EmergencyContact;
import background.Hostel;
import background.Room;
import background.School;
import background.Student;
import database.DBConnection;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import java.awt.Font;
import java.awt.Color;

import javax.swing.JMenu;

import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form MainWindow
	 */

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

	public MainWindow() {
		setTitle("Dormitory Management System");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();
		jMenuBar3 = new javax.swing.JMenuBar();
		jMenu6 = new javax.swing.JMenu();
		jMenu7 = new javax.swing.JMenu();
		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jSeparator1 = new javax.swing.JSeparator();
		mainSearchPanel = new javax.swing.JPanel();
		searchStudentLabel = new javax.swing.JLabel();
		searchScrollPane = new javax.swing.JScrollPane();
		searchStudentList = new javax.swing.JList();
		searchModel = new DefaultListModel();
		fillStudentList();
		searchStudentList = new JList(searchModel);
		searchStudentList.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent evt) {
				clickStudentSearchList(evt);
			}
		});
		searchStudentText = new javax.swing.JTextField();
		searchButton = new javax.swing.JButton();
		searchButton.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent evt) {
				clickSearchButton(evt);
			}
		});

		mainPanePanel = new javax.swing.JPanel();
		tabbedPane = new javax.swing.JTabbedPane();
		mainPaneSubPanel = new javax.swing.JPanel();
		personalInfoPanel = new javax.swing.JPanel();
		personalInfoLabel = new javax.swing.JLabel();
		personalInfoNameLabel = new javax.swing.JLabel();
		personalInfoSurnameLabel = new javax.swing.JLabel();
		personalInfoNationalIDLabel = new javax.swing.JLabel();
		personalInfoGenderLabel = new javax.swing.JLabel();
		personalInfoPhoneLabel = new javax.swing.JLabel();
		personalInfoMailLabel = new javax.swing.JLabel();
		personalInfoBirthdayLabel = new javax.swing.JLabel();
		stdNameText = new javax.swing.JTextField();
		stdSurnameTExt = new javax.swing.JTextField();
		stdTCText = new javax.swing.JTextField();
		stdPhoneText = new javax.swing.JTextField();
		stdMailText = new javax.swing.JTextField();
		stdGenderCBox = new javax.swing.JComboBox();
		emergencyContactPanel = new javax.swing.JPanel();
		emergencyContactLabel = new javax.swing.JLabel();
		emergencyContactNameLabel = new javax.swing.JLabel();
		emergencyContactSurnameLabel = new javax.swing.JLabel();
		emergencyContactPhoneLabel = new javax.swing.JLabel();
		emgNameText = new javax.swing.JTextField();
		emgSurnameText = new javax.swing.JTextField();
		emgPhoneText = new javax.swing.JTextField();
		schoolInfoPanel = new javax.swing.JPanel();
		schoolInfoLabel = new javax.swing.JLabel();
		schoolInfoUniversityLabel = new javax.swing.JLabel();
		schoolInfoDepartmentLabel = new javax.swing.JLabel();
		schoolInfoGradeLabel = new javax.swing.JLabel();
		schUniNameText = new javax.swing.JTextField();
		schDeptNameText = new javax.swing.JTextField();
		schGradeText = new javax.swing.JTextField();
		accoInfoPanel = new javax.swing.JPanel();
		accoInfoLabel = new javax.swing.JLabel();
		accoInfoDormLabel = new javax.swing.JLabel();
		accoInfoRoomLabel = new javax.swing.JLabel();
		accDormCBox = new javax.swing.JComboBox();
		accRoomCBox = new javax.swing.JComboBox();
		accoInfoStartDateLabel = new javax.swing.JLabel();
		accoInfoEndDateLabel = new javax.swing.JLabel();
		accStartDateText = new javax.swing.JTextField();
		accEndDateText = new javax.swing.JTextField();
		saveButton = new javax.swing.JButton();
		saveButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				try {
					clickSaveButton(evt);
				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		paymentPanel = new javax.swing.JPanel();
		menuBar = new javax.swing.JMenuBar();
		homeMenu = new javax.swing.JMenu();
		addStudentMenuItem = new javax.swing.JMenuItem();
		dormMenu = new javax.swing.JMenu();
		addDormMenuItem = new javax.swing.JMenuItem();
		roomMenu = new javax.swing.JMenu();
		addRoomMenuItem = new javax.swing.JMenuItem();
		otherMenu = new javax.swing.JMenu();
		addOtherChartMenuItem = new javax.swing.JMenuItem();

		setEditableFalse();

		jMenu3.setText("File");
		jMenuBar2.add(jMenu3);

		jMenu4.setText("Edit");
		jMenuBar2.add(jMenu4);

		jMenu6.setText("File");
		jMenuBar3.add(jMenu6);

		jMenu7.setText("Edit");
		jMenuBar3.add(jMenu7);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jSeparator1.setBackground(new java.awt.Color(255, 51, 0));
		jSeparator1.setForeground(new java.awt.Color(255, 51, 0));
		jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

		searchStudentLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		searchStudentLabel.setText("             Search Student");

		searchStudentList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		// searchStudentList.setModel(new javax.swing.AbstractListModel() {
		// public String[] getList() {
		// DBConnection conn = new DBConnection();
		// String studentArray[] = null;
		// try {
		// ArrayList<String> studenNameSurname = conn
		// .displayStudentNameSurname();
		// studentArray = new String[studenNameSurname.size()];
		// for (int i = 0; i < studentArray.length; i++) {
		// studentArray[i] = studenNameSurname.get(i);
		// }
		//
		// } catch (Exception e) {
		// e.printStackTrace();
		// }
		// return studentArray;
		// }
		// String[] strings = getList();
		//
		// public int getSize() {
		// return strings.length;
		// }
		//
		// public Object getElementAt(int i) {
		// return strings[i];
		// }
		// });
		searchScrollPane.setViewportView(searchStudentList);

		searchStudentText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

		searchButton.setBackground(new java.awt.Color(204, 255, 204));
		searchButton.setText("Q");

		javax.swing.GroupLayout gl_mainSearchPanel = new javax.swing.GroupLayout(
				mainSearchPanel);
		mainSearchPanel.setLayout(gl_mainSearchPanel);
		gl_mainSearchPanel
				.setHorizontalGroup(gl_mainSearchPanel
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_mainSearchPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_mainSearchPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																searchScrollPane)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																gl_mainSearchPanel
																		.createSequentialGroup()
																		.addComponent(
																				searchStudentText)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				searchButton))
														.addComponent(
																searchStudentLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																212,
																Short.MAX_VALUE))
										.addContainerGap(22, Short.MAX_VALUE)));
		gl_mainSearchPanel
				.setVerticalGroup(gl_mainSearchPanel
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_mainSearchPanel
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												searchStudentLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												gl_mainSearchPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																searchStudentText)
														.addComponent(
																searchButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																34,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(searchScrollPane)
										.addContainerGap()));

		tabbedPane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		mainPaneSubPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(
				javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51,
						204, 0), new java.awt.Color(51, 153, 0),
				new java.awt.Color(0, 153, 0), new java.awt.Color(51, 153, 0)));

		personalInfoPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		personalInfoLabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
		personalInfoLabel.setText("Personal Information");

		personalInfoNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoNameLabel.setText("Name:");

		personalInfoSurnameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoSurnameLabel.setText("Surname:");

		personalInfoNationalIDLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoNationalIDLabel.setText("TC ID No:");

		personalInfoGenderLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoGenderLabel.setText("Gender:");

		personalInfoPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoPhoneLabel.setText("Phone:");

		personalInfoMailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoMailLabel.setText("E-mail:");

		personalInfoBirthdayLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		personalInfoBirthdayLabel.setText("Birthday:");

		stdBirthdayText = new JTextField();
		stdBirthdayText.setColumns(10);

		javax.swing.GroupLayout gl_personalInfoPanel = new javax.swing.GroupLayout(
				personalInfoPanel);
		gl_personalInfoPanel
				.setHorizontalGroup(gl_personalInfoPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_personalInfoPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_personalInfoPanel
														.createParallelGroup(
																Alignment.LEADING)
														.addComponent(
																personalInfoLabel,
																GroupLayout.PREFERRED_SIZE,
																123,
																GroupLayout.PREFERRED_SIZE)
														.addGroup(
																gl_personalInfoPanel
																		.createSequentialGroup()
																		.addGroup(
																				gl_personalInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addGroup(
																								gl_personalInfoPanel
																										.createSequentialGroup()
																										.addGroup(
																												gl_personalInfoPanel
																														.createParallelGroup(
																																Alignment.TRAILING,
																																false)
																														.addComponent(
																																personalInfoGenderLabel,
																																Alignment.LEADING,
																																GroupLayout.DEFAULT_SIZE,
																																GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																personalInfoNationalIDLabel,
																																Alignment.LEADING,
																																GroupLayout.DEFAULT_SIZE,
																																63,
																																Short.MAX_VALUE)
																														.addComponent(
																																personalInfoSurnameLabel,
																																Alignment.LEADING,
																																GroupLayout.DEFAULT_SIZE,
																																GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE))
																										.addGap(18)
																										.addGroup(
																												gl_personalInfoPanel
																														.createParallelGroup(
																																Alignment.LEADING)
																														.addComponent(
																																stdSurnameTExt)
																														.addComponent(
																																stdTCText)
																														.addGroup(
																																gl_personalInfoPanel
																																		.createSequentialGroup()
																																		.addComponent(
																																				stdGenderCBox,
																																				GroupLayout.PREFERRED_SIZE,
																																				97,
																																				GroupLayout.PREFERRED_SIZE)
																																		.addGap(0,
																																				115,
																																				Short.MAX_VALUE))))
																						.addGroup(
																								gl_personalInfoPanel
																										.createSequentialGroup()
																										.addComponent(
																												personalInfoNameLabel,
																												GroupLayout.PREFERRED_SIZE,
																												63,
																												GroupLayout.PREFERRED_SIZE)
																										.addGap(18)
																										.addComponent(
																												stdNameText)))
																		.addGap(61)
																		.addGroup(
																				gl_personalInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addComponent(
																								personalInfoPhoneLabel,
																								GroupLayout.DEFAULT_SIZE,
																								50,
																								Short.MAX_VALUE)
																						.addComponent(
																								personalInfoMailLabel,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								personalInfoBirthdayLabel))
																		.addGap(37)
																		.addGroup(
																				gl_personalInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addComponent(
																								stdBirthdayText)
																						.addComponent(
																								stdPhoneText,
																								GroupLayout.DEFAULT_SIZE,
																								223,
																								Short.MAX_VALUE)
																						.addComponent(
																								stdMailText))))
										.addContainerGap(69, Short.MAX_VALUE)));
		gl_personalInfoPanel
				.setVerticalGroup(gl_personalInfoPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_personalInfoPanel
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(personalInfoLabel)
										.addGap(11)
										.addGroup(
												gl_personalInfoPanel
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																personalInfoNameLabel,
																GroupLayout.PREFERRED_SIZE,
																15,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																personalInfoPhoneLabel)
														.addComponent(
																stdNameText,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																stdPhoneText,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.UNRELATED)
										.addGroup(
												gl_personalInfoPanel
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																personalInfoSurnameLabel)
														.addComponent(
																personalInfoMailLabel)
														.addComponent(
																stdSurnameTExt,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																stdMailText,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.UNRELATED)
										.addGroup(
												gl_personalInfoPanel
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																personalInfoNationalIDLabel)
														.addComponent(
																personalInfoBirthdayLabel)
														.addComponent(
																stdTCText,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																stdBirthdayText,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.RELATED, 18,
												Short.MAX_VALUE)
										.addGroup(
												gl_personalInfoPanel
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																personalInfoGenderLabel)
														.addComponent(
																stdGenderCBox,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
		personalInfoPanel.setLayout(gl_personalInfoPanel);

		emergencyContactPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		emergencyContactLabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
		emergencyContactLabel.setText("Emergency Contact");

		emergencyContactNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		emergencyContactNameLabel.setText("Name:");

		emergencyContactSurnameLabel
				.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		emergencyContactSurnameLabel.setText("Surname:");

		emergencyContactPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		emergencyContactPhoneLabel.setText("Phone:");

		javax.swing.GroupLayout gl_emergencyContactPanel = new javax.swing.GroupLayout(
				emergencyContactPanel);
		emergencyContactPanel.setLayout(gl_emergencyContactPanel);
		gl_emergencyContactPanel
				.setHorizontalGroup(gl_emergencyContactPanel
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_emergencyContactPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_emergencyContactPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																emergencyContactLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																125,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																gl_emergencyContactPanel
																		.createSequentialGroup()
																		.addGroup(
																				gl_emergencyContactPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								emergencyContactPhoneLabel,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								emergencyContactSurnameLabel,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								62,
																								Short.MAX_VALUE)
																						.addComponent(
																								emergencyContactNameLabel,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_emergencyContactPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								emgSurnameText)
																						.addComponent(
																								emgNameText)
																						.addComponent(
																								emgPhoneText,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								214,
																								Short.MAX_VALUE))))
										.addContainerGap(47, Short.MAX_VALUE)));
		gl_emergencyContactPanel
				.setVerticalGroup(gl_emergencyContactPanel
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_emergencyContactPanel
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(emergencyContactLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												gl_emergencyContactPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																emergencyContactNameLabel)
														.addComponent(
																emgNameText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												gl_emergencyContactPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																emergencyContactSurnameLabel)
														.addComponent(
																emgSurnameText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												gl_emergencyContactPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																emergencyContactPhoneLabel)
														.addComponent(
																emgPhoneText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		schoolInfoPanel.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		schoolInfoLabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
		schoolInfoLabel.setText("School Information");

		schoolInfoUniversityLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		schoolInfoUniversityLabel.setText("University:");

		schoolInfoDepartmentLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		schoolInfoDepartmentLabel.setText("Department:");

		schoolInfoGradeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		schoolInfoGradeLabel.setText("Grade:");

		javax.swing.GroupLayout gl_schoolInfoPanel = new javax.swing.GroupLayout(
				schoolInfoPanel);
		schoolInfoPanel.setLayout(gl_schoolInfoPanel);
		gl_schoolInfoPanel
				.setHorizontalGroup(gl_schoolInfoPanel
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_schoolInfoPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_schoolInfoPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																schoolInfoLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																114,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																gl_schoolInfoPanel
																		.createSequentialGroup()
																		.addGroup(
																				gl_schoolInfoPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addComponent(
																								schoolInfoGradeLabel,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								schoolInfoDepartmentLabel,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								79,
																								Short.MAX_VALUE)
																						.addComponent(
																								schoolInfoUniversityLabel,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				gl_schoolInfoPanel
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								schUniNameText)
																						.addComponent(
																								schDeptNameText)
																						.addComponent(
																								schGradeText,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								220,
																								Short.MAX_VALUE))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		gl_schoolInfoPanel
				.setVerticalGroup(gl_schoolInfoPanel
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_schoolInfoPanel
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(schoolInfoLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												gl_schoolInfoPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																schoolInfoUniversityLabel)
														.addComponent(
																schUniNameText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												gl_schoolInfoPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																schDeptNameText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																schoolInfoDepartmentLabel))
										.addGap(18, 18, 18)
										.addGroup(
												gl_schoolInfoPanel
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																schGradeText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																schoolInfoGradeLabel))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		accoInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		accoInfoLabel.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
		accoInfoLabel.setText("Accomadation Information");

		accoInfoDormLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		accoInfoDormLabel.setText("Dorm:");

		accoInfoRoomLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		accoInfoRoomLabel.setText("Room:");

		accoInfoStartDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		accoInfoStartDateLabel.setText("Start Date:");

		accoInfoEndDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		accoInfoEndDateLabel.setText("End Date:");

		saveButton.setBackground(new Color(204, 255, 204));
		saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		saveButton.setText("SAVE");

		JButton editButton = new JButton("EDIT");
		editButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				clickEditButton(evt);
			}
		});
		editButton.setBackground(new Color(204, 255, 204));
		editButton.setFont(new Font("Tahoma", Font.BOLD, 12));

		javax.swing.GroupLayout gl_accoInfoPanel = new javax.swing.GroupLayout(
				accoInfoPanel);
		gl_accoInfoPanel
				.setHorizontalGroup(gl_accoInfoPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_accoInfoPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_accoInfoPanel
														.createParallelGroup(
																Alignment.LEADING)
														.addComponent(
																accoInfoLabel,
																GroupLayout.PREFERRED_SIZE,
																165,
																GroupLayout.PREFERRED_SIZE)
														.addGroup(
																gl_accoInfoPanel
																		.createSequentialGroup()
																		.addGroup(
																				gl_accoInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addGroup(
																								gl_accoInfoPanel
																										.createSequentialGroup()
																										.addComponent(
																												accoInfoDormLabel)
																										.addGap(29))
																						.addGroup(
																								gl_accoInfoPanel
																										.createSequentialGroup()
																										.addComponent(
																												accoInfoRoomLabel,
																												GroupLayout.DEFAULT_SIZE,
																												55,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												ComponentPlacement.RELATED)))
																		.addGroup(
																				gl_accoInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addComponent(
																								accRoomCBox,
																								0,
																								GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								accDormCBox,
																								0,
																								92,
																								Short.MAX_VALUE))
																		.addGap(70)
																		.addGroup(
																				gl_accoInfoPanel
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addComponent(
																								accoInfoStartDateLabel,
																								GroupLayout.PREFERRED_SIZE,
																								83,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								accoInfoEndDateLabel,
																								GroupLayout.PREFERRED_SIZE,
																								83,
																								GroupLayout.PREFERRED_SIZE))
																		.addGap(18)
																		.addGroup(
																				gl_accoInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addGroup(
																								gl_accoInfoPanel
																										.createSequentialGroup()
																										.addComponent(
																												accStartDateText,
																												GroupLayout.PREFERRED_SIZE,
																												215,
																												GroupLayout.PREFERRED_SIZE)
																										.addGap(65)
																										.addComponent(
																												editButton,
																												GroupLayout.DEFAULT_SIZE,
																												61,
																												Short.MAX_VALUE))
																						.addGroup(
																								gl_accoInfoPanel
																										.createSequentialGroup()
																										.addComponent(
																												accEndDateText,
																												GroupLayout.PREFERRED_SIZE,
																												215,
																												GroupLayout.PREFERRED_SIZE)
																										.addGap(65)
																										.addComponent(
																												saveButton,
																												GroupLayout.DEFAULT_SIZE,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)))))
										.addGap(20)));
		gl_accoInfoPanel
				.setVerticalGroup(gl_accoInfoPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_accoInfoPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_accoInfoPanel
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																gl_accoInfoPanel
																		.createSequentialGroup()
																		.addComponent(
																				accoInfoLabel)
																		.addPreferredGap(
																				ComponentPlacement.UNRELATED)
																		.addGroup(
																				gl_accoInfoPanel
																						.createParallelGroup(
																								Alignment.BASELINE)
																						.addComponent(
																								accoInfoDormLabel)
																						.addComponent(
																								accDormCBox,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								accoInfoStartDateLabel)
																						.addComponent(
																								accStartDateText,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				gl_accoInfoPanel
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addGroup(
																								gl_accoInfoPanel
																										.createSequentialGroup()
																										.addGap(17)
																										.addGroup(
																												gl_accoInfoPanel
																														.createParallelGroup(
																																Alignment.BASELINE)
																														.addComponent(
																																accRoomCBox,
																																GroupLayout.PREFERRED_SIZE,
																																GroupLayout.DEFAULT_SIZE,
																																GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																accoInfoRoomLabel)))
																						.addGroup(
																								gl_accoInfoPanel
																										.createSequentialGroup()
																										.addGap(18)
																										.addGroup(
																												gl_accoInfoPanel
																														.createParallelGroup(
																																Alignment.BASELINE)
																														.addComponent(
																																accEndDateText,
																																GroupLayout.PREFERRED_SIZE,
																																GroupLayout.DEFAULT_SIZE,
																																GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																accoInfoEndDateLabel)))))
														.addGroup(
																gl_accoInfoPanel
																		.createSequentialGroup()
																		.addGap(19)
																		.addComponent(
																				editButton)
																		.addPreferredGap(
																				ComponentPlacement.UNRELATED)
																		.addComponent(
																				saveButton,
																				GroupLayout.PREFERRED_SIZE,
																				23,
																				GroupLayout.PREFERRED_SIZE)))
										.addGap(29)));
		accoInfoPanel.setLayout(gl_accoInfoPanel);

		javax.swing.GroupLayout gl_mainPaneSubPanel = new javax.swing.GroupLayout(
				mainPaneSubPanel);
		gl_mainPaneSubPanel
				.setHorizontalGroup(gl_mainPaneSubPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								Alignment.TRAILING,
								gl_mainPaneSubPanel
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												gl_mainPaneSubPanel
														.createParallelGroup(
																Alignment.TRAILING)
														.addComponent(
																accoInfoPanel,
																Alignment.LEADING,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																personalInfoPanel,
																Alignment.LEADING,
																GroupLayout.DEFAULT_SIZE,
																722,
																Short.MAX_VALUE)
														.addGroup(
																Alignment.LEADING,
																gl_mainPaneSubPanel
																		.createSequentialGroup()
																		.addComponent(
																				emergencyContactPanel,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				ComponentPlacement.RELATED)
																		.addComponent(
																				schoolInfoPanel,
																				GroupLayout.DEFAULT_SIZE,
																				361,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		gl_mainPaneSubPanel
				.setVerticalGroup(gl_mainPaneSubPanel
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								gl_mainPaneSubPanel
										.createSequentialGroup()
										.addComponent(personalInfoPanel,
												GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addGroup(
												gl_mainPaneSubPanel
														.createParallelGroup(
																Alignment.LEADING,
																false)
														.addComponent(
																emergencyContactPanel,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																schoolInfoPanel,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(accoInfoPanel,
												GroupLayout.PREFERRED_SIZE,
												120, Short.MAX_VALUE)
										.addContainerGap()));
		mainPaneSubPanel.setLayout(gl_mainPaneSubPanel);

		tabbedPane.addTab("Profile", mainPaneSubPanel);

		javax.swing.GroupLayout gl_paymentPanel = new javax.swing.GroupLayout(
				paymentPanel);
		paymentPanel.setLayout(gl_paymentPanel);
		gl_paymentPanel.setHorizontalGroup(gl_paymentPanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 746,
				Short.MAX_VALUE));
		gl_paymentPanel.setVerticalGroup(gl_paymentPanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 454,
				Short.MAX_VALUE));

		tabbedPane.addTab("Payment", paymentPanel);

		javax.swing.GroupLayout gl_mainPanePanel = new javax.swing.GroupLayout(
				mainPanePanel);
		mainPanePanel.setLayout(gl_mainPanePanel);
		gl_mainPanePanel.setHorizontalGroup(gl_mainPanePanel
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						gl_mainPanePanel.createSequentialGroup()
								.addContainerGap().addComponent(tabbedPane)
								.addContainerGap()));
		gl_mainPanePanel.setVerticalGroup(gl_mainPanePanel.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				gl_mainPanePanel.createSequentialGroup().addGap(20, 20, 20)
						.addComponent(tabbedPane).addContainerGap()));

		homeMenu.setText("Home");

		addStudentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_S,
				java.awt.event.InputEvent.SHIFT_MASK));
		addStudentMenuItem.setText("Add Student");
		addStudentMenuItem
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						addStudentActionPerformed(evt);
					}
				});
		homeMenu.add(addStudentMenuItem);

		menuBar.add(homeMenu);

		dormMenu.setText("Dorm");

		addDormMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_D,
				java.awt.event.InputEvent.SHIFT_MASK));
		addDormMenuItem.setText("Add Dorm");
		addDormMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addDormActionPerformed(evt);
			}
		});
		dormMenu.add(addDormMenuItem);

		menuBar.add(dormMenu);

		viewDormMenuItem = new JMenuItem("View Dorm List");
		viewDormMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				viewDormActionPerformed(evt);
			}
		});
		dormMenu.add(viewDormMenuItem);

		roomMenu.setText("Room");

		addRoomMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(
				java.awt.event.KeyEvent.VK_R,
				java.awt.event.InputEvent.SHIFT_MASK));
		addRoomMenuItem.setText("Add Room");
		addRoomMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addRoomActionPerformed(evt);
			}
		});
		roomMenu.add(addRoomMenuItem);

		menuBar.add(roomMenu);
		mntmAddRoomType = new JMenuItem("Add Room Type");
		mntmAddRoomType.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addRoomTypeActionPerformed(evt);
			}

			private void addRoomTypeActionPerformed(ActionEvent evt) {
				new RoomTypeWindow().setVisible(true);

			}
		});
		roomMenu.add(mntmAddRoomType);

		searchMenu = new JMenu("Search");
		menuBar.add(searchMenu);

		searchAllMenuItem = new JMenuItem("Search All   Ctrl+F");
		searchMenu.add(searchAllMenuItem);

		otherMenu.setText("Other");
		menuBar.add(otherMenu);

		lostItemsMenuItem = new JMenuItem("Lost Items");
		lostItemsMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				new AddLostItemWindow().setVisible(true);
			}
		});
		otherMenu.add(lostItemsMenuItem);

		addRoomMenuItem = new JMenuItem("Show Capacity of Dorms");
		addRoomMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ChartChooserView chooser = new ChartChooserView();
				// chooser.setVisible(true);
				chooser.pack();
				RefineryUtilities.centerFrameOnScreen(chooser);
				chooser.setVisible(true);

			}
		});
		otherMenu.add(addRoomMenuItem);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(mainSearchPanel,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jSeparator1,
																		GroupLayout.PREFERRED_SIZE,
																		15,
																		GroupLayout.PREFERRED_SIZE)
																.addContainerGap(
																		781,
																		Short.MAX_VALUE))
												.addComponent(
														mainPanePanel,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE,
						GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addComponent(mainSearchPanel, GroupLayout.DEFAULT_SIZE, 540,
						Short.MAX_VALUE)
				.addComponent(mainPanePanel, GroupLayout.DEFAULT_SIZE, 540,
						Short.MAX_VALUE));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void fillStudentList() {
		DBConnection conn = new DBConnection();
		String studentArray[] = null;
		try {
			ArrayList<String> studenNameSurname = conn
					.displayStudentNameSurname();
			studentArray = new String[studenNameSurname.size()];
			for (int i = 0; i < studentArray.length; i++) {
				studentArray[i] = studenNameSurname.get(i);
				searchModel.addElement(studenNameSurname.get(i));
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clickStudentSearchList(MouseEvent evt) {
		accDormCBox.removeAllItems();
		accRoomCBox.removeAllItems();
		stdGenderCBox.removeAllItems();
		DBConnection conn = new DBConnection();
		Student std = new Student();
		EmergencyContact emg = new EmergencyContact();
		School sch = new School();
		Hostel host = new Hostel();
		Dorm dorm = new Dorm();
		Room room = new Room();
		name = new String[2];
		String selected = searchStudentList.getSelectedValue().toString();
		for (int j = 0; j < name.length; j++) {
			name = searchStudentList.getSelectedValue().toString()
					.split("\\s+");
		}
		if (!name[0].equals(null) && !name[1].equals(null)) {
			std = conn.retrieveStudentInfo(name[0], name[1]);
			emg = conn.retrieveEmergencyInfo(name[0], name[1]);
			sch = conn.retrieveSchoolInfo(name[0], name[1]);
			dorm = conn.retrieveDormInfo(name[0], name[1]);
			room = conn.retrieveRoomInfo(name[0], name[1]);
			host = conn.retrieveHostelInfo(name[0], name[1]);
		}

		if (evt.getClickCount() == 2) {
			fillStudentInfo(std);
			fillEmergencyContact(emg);
			fillSchoolInfo(sch);
			fillAccInfo(dorm, room);
		}
	}

	private void fillAccInfo(Dorm dorm, Room room) {
		accDormCBox.addItem(dorm.getDormName());
		// accRoomType.addItem(room.getTypeName());
		accRoomCBox.addItem(room.getRoomNo());
		// accStartDateText.setText(host.getStartDate());
		// accEndDateText.setText(host.getEndDate());
	}

	private void fillSchoolInfo(School sch) {
		schUniNameText.setText(sch.getUniName());
		schDeptNameText.setText(sch.getDepartment());
		if (sch.getGrade() != 0)
			schGradeText.setText(Integer.toString(sch.getGrade()));
	}

	private void fillStudentInfo(Student std) {
		stdNameText.setText(std.getName());
		stdSurnameTExt.setText(std.getSurname());
		stdMailText.setText(std.getEmail());
		stdGenderCBox.addItem(std.getGender());
		// stdBirthdayText.setText(std.getBirthday().toString());
		if (!std.getTC().equals("0"))
			stdTCText.setText(std.getTC());
		stdPhoneText.setText(std.getPhone());
	}

	private void fillEmergencyContact(EmergencyContact emg) {
		emgNameText.setText(emg.getName());
		emgSurnameText.setText(emg.getSurname());
		emgPhoneText.setText(emg.getPhone());
	}

	private void clickSearchButton(MouseEvent evt) {
		int pos = 0;
		if (searchStudentText.getText().isEmpty()) {
			fillStudentList();
		}
		DBConnection conn = new DBConnection();
		studentList = new ArrayList<String>();
		try {
			studentList = conn.displayStudentNameSurname();
			ArrayList<String> st = new ArrayList<String>();
			String[] stdAll = new String[studentList.size() * 2];
			if (searchStudentText.getText().isEmpty()) {

				// JOptionPane.showMessageDialog(getContentPane(),
				// "Please type a name!");
			} else {
				String seachText = searchStudentText.getText();
				for (int i = 0; i < studentList.size(); i++) {
					stdAll = studentList.get(i).split("\\s+");
					st.add(stdAll[0]);
					st.add(stdAll[1]);
					stdAll = null;
				}
				if (st.contains(seachText)) {
					searchModel.removeAllElements();
					int position = st.indexOf(seachText);
					pos = position / 2;
					searchModel.addElement(studentList.get(pos));

					// searchModel.addElement(seachText);
				} else if (studentList.contains(seachText)) {
					searchModel.removeAllElements();
					searchModel.addElement(seachText);
				}
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void clickEditButton(ActionEvent evt) {
		setEditableTrue();

	}

	private void clickSaveButton(ActionEvent evt) throws ParseException {
		DBConnection db = new DBConnection();
		Student student = getStudentInfoFromText();
		EmergencyContact emgContact = getContactInfoFromText();
		School school = getSchoolInfoFromText();
		Dorm dorm = new Dorm();
		dorm.setDormName(accDormCBox.getSelectedItem().toString());
		Room room = getRoomFromText();

		Hostel hostel = getStartEndDateFromText();
		String Name = name[0];

		String Surname = name[1];
		db.updateStudent(student, emgContact, dorm, room, hostel, school, Name,
				Surname);

		setEditableFalse();

	}

	private Hostel getStartEndDateFromText() throws ParseException {
		Hostel hostel = new Hostel();
		Date start = convertStringToDatetime(accStartDateText.getText());
		hostel.setStartDate(start);
		Date end = convertStringToDatetime(accEndDateText.getText());
		hostel.setEndDate(end);

		return hostel;

	}

	private Room getRoomFromText() {
		Room room = new Room();
		int roomNo = Integer.parseInt(accRoomCBox.getSelectedItem().toString());
		room.setRoomNo(roomNo);
		return room;
	}

	private School getSchoolInfoFromText() {
		School school = new School();
		school.setUniName(schUniNameText.getText());
		school.setDepartment(schDeptNameText.getText());
		if (schGradeText.getText().isEmpty()) {
			school.setGrade(0);
		} else {
			int grade = Integer.parseInt(schGradeText.getText());
			school.setGrade(grade);
		}
		return school;
	}

	private EmergencyContact getContactInfoFromText() {
		EmergencyContact emgContact = new EmergencyContact();
		emgContact.setName(emgNameText.getText());
		emgContact.setSurname(emgSurnameText.getText());
		emgContact.setPhone(emgSurnameText.getText());
		return emgContact;
	}

	private Student getStudentInfoFromText() throws ParseException {
		Student student = new Student();
		if (stdBirthdayText.getText().isEmpty()) {
			student.setBirthday(null);
		} else {
			Date birthday = convertStringToDatetime(stdBirthdayText.getText());
			student.setBirthday(birthday);
		}

		student.setName(stdNameText.getText());
		student.setSurname(stdSurnameTExt.getText());
		student.setEmail(stdMailText.getText());
		student.setGender(stdGenderCBox.getSelectedItem().toString());
		student.setTC(stdTCText.getText());
		student.setPhone(stdPhoneText.getText());

		return student;
	}

	private Date convertStringToDatetime(String dt) throws ParseException {
		java.util.Date date = new java.util.Date();
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		date = sdf.parse(dt);
		Date sqlDate = new java.sql.Date(date.getTime());
		return sqlDate;
	}

	private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		new StudentWindow().setVisible(true);
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void addDormActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		new DormWindow().setVisible(true);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void addRoomActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		new RoomWindow().setVisible(true);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void viewDormActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		new DormListWindow().setVisible(true);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void setEditableFalse() {
		stdNameText.setEditable(false);
		stdSurnameTExt.setEditable(false);
		stdTCText.setEditable(false);
		stdPhoneText.setEditable(false);
		stdMailText.setEditable(false);
		stdGenderCBox.setEnabled(false);
		emgNameText.setEditable(false);
		emgSurnameText.setEditable(false);
		emgPhoneText.setEditable(false);
		schUniNameText.setEditable(false);
		schDeptNameText.setEditable(false);
		schGradeText.setEditable(false);
		accDormCBox.setEnabled(false);
		accRoomCBox.setEnabled(false);
		accStartDateText.setEditable(false);
		accEndDateText.setEditable(false);
	}

	private void setEditableTrue() {
		stdNameText.setEditable(true);
		stdSurnameTExt.setEditable(true);
		stdTCText.setEditable(true);
		stdPhoneText.setEditable(true);
		stdMailText.setEditable(true);
		stdGenderCBox.setEnabled(true);
		emgNameText.setEditable(true);
		emgSurnameText.setEditable(true);
		emgPhoneText.setEditable(true);
		schUniNameText.setEditable(true);
		schDeptNameText.setEditable(true);
		schGradeText.setEditable(true);
		accDormCBox.setEnabled(true);
		accRoomCBox.setEnabled(true);
		accStartDateText.setEditable(true);
		accEndDateText.setEditable(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.JButton searchButton;
	private javax.swing.JComboBox stdGenderCBox;
	private javax.swing.JList searchStudentList;
	private javax.swing.JMenu homeMenu;
	private javax.swing.JMenu dormMenu;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu roomMenu;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenu jMenu7;
	private javax.swing.JMenu otherMenu;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuBar jMenuBar3;
	private javax.swing.JMenuItem addStudentMenuItem;
	private javax.swing.JMenuItem addDormMenuItem;
	private javax.swing.JMenuItem addRoomMenuItem;
	private javax.swing.JMenuItem addOtherChartMenuItem;
	private javax.swing.JScrollPane searchScrollPane;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTabbedPane tabbedPane;
	private javax.swing.JTextField schUniNameText;
	private javax.swing.JTextField schDeptNameText;
	private javax.swing.JTextField schGradeText;
	private javax.swing.JTextField emgNameText;
	private javax.swing.JTextField emgSurnameText;
	private javax.swing.JTextField emgPhoneText;
	private javax.swing.JComboBox accDormCBox;
	private javax.swing.JTextField stdMailText;
	private javax.swing.JTextField accEndDateText;
	private javax.swing.JTextField stdNameText;
	private javax.swing.JTextField stdPhoneText;
	private javax.swing.JComboBox accRoomCBox;
	private javax.swing.JButton saveButton;
	private JMenuItem mntmAddRoomType;
	private javax.swing.JTextField accStartDateText;
	private javax.swing.JTextField stdSurnameTExt;
	private javax.swing.JTextField stdTCText;
	private javax.swing.JTextField searchStudentText;
	private JMenuItem viewDormMenuItem;
	private JMenu searchMenu;
	private JMenuItem searchAllMenuItem;
	private JMenuItem lostItemsMenuItem;
	private javax.swing.JPanel mainSearchPanel;
	private javax.swing.JPanel mainPanePanel;
	private javax.swing.JPanel mainPaneSubPanel;
	private javax.swing.JPanel paymentPanel;
	private javax.swing.JPanel personalInfoPanel;
	private javax.swing.JPanel emergencyContactPanel;
	private javax.swing.JPanel schoolInfoPanel;
	private javax.swing.JPanel accoInfoPanel;
	private javax.swing.JLabel personalInfoLabel;
	private javax.swing.JLabel personalInfoPhoneLabel;
	private javax.swing.JLabel personalInfoMailLabel;
	private javax.swing.JLabel personalInfoBirthdayLabel;
	private javax.swing.JLabel emergencyContactNameLabel;
	private javax.swing.JLabel emergencyContactSurnameLabel;
	private javax.swing.JLabel emergencyContactPhoneLabel;
	private javax.swing.JLabel schoolInfoUniversityLabel;
	private javax.swing.JLabel schoolInfoDepartmentLabel;
	private javax.swing.JLabel schoolInfoGradeLabel;
	private javax.swing.JLabel accoInfoDormLabel;
	private javax.swing.JLabel searchStudentLabel;
	private javax.swing.JLabel accoInfoRoomLabel;
	private javax.swing.JLabel accoInfoStartDateLabel;
	private javax.swing.JLabel accoInfoEndDateLabel;
	private javax.swing.JLabel emergencyContactLabel;
	private javax.swing.JLabel schoolInfoLabel;
	private javax.swing.JLabel accoInfoLabel;
	private javax.swing.JLabel personalInfoNameLabel;
	private javax.swing.JLabel personalInfoSurnameLabel;
	private javax.swing.JLabel personalInfoNationalIDLabel;
	private javax.swing.JLabel personalInfoGenderLabel;
	private JTextField stdBirthdayText;
	private ArrayList<String> studentList;
	private DefaultListModel searchModel;
	private String[] name;
}
