 * To change this license header, choose License Headers in Project Properties.
package view;

import java.sql.SQLException;

public class RoomWindow extends javax.swing.JFrame {
	final JComboBox cboxDorm = new JComboBox();
	final JComboBox cboxRoomType = new JComboBox();

	/**
	 * Creates new form StudentWindow
	 */
	public RoomWindow() {
		setTitle("Add Room");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		dormAddDutton = new javax.swing.JButton();
		roomDormNumberLabel = new javax.swing.JLabel();
		roomRoomNumberLabel = new javax.swing.JLabel();
		roomRoomTypeLabel = new javax.swing.JLabel();
		roomAddButton = new javax.swing.JButton();

		dormAddDutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		dormAddDutton.setText("ADD");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		roomDormNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomDormNumberLabel.setText("Dorm :");

		roomRoomNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomRoomNumberLabel.setText("Room Type :");

		roomRoomTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		roomRoomTypeLabel.setText("Room No :");

		roomAddButton.setBackground(new java.awt.Color(204, 255, 204));
		roomAddButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		roomAddButton.setText("ADD");
		roomAddButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					addRoomButtonActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
		fillCBoxRoomType();
		cboxRoomType.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				displayRoomTypeAction(evt);
			}
		});

		fillCBoxDorm();
		cboxDorm.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				displayDormBoxAction(evt);
			}
		});

		listModelRoom = new DefaultListModel();
		roomNoLst = new JList(listModelRoom);
		roomNoLst.setFont(new Font("Tahoma", Font.PLAIN, 12));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.TRAILING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING)
																				.addComponent(
																						roomDormNumberLabel,
																						GroupLayout.DEFAULT_SIZE,
																						143,
																						Short.MAX_VALUE)
																				.addComponent(
																						roomRoomNumberLabel,
																						GroupLayout.DEFAULT_SIZE,
																						143,
																						Short.MAX_VALUE))
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING)
																				.addComponent(
																						cboxRoomType,
																						0,
																						120,
																						Short.MAX_VALUE)
																				.addComponent(
																						cboxDorm,
																						Alignment.TRAILING,
																						0,
																						120,
																						Short.MAX_VALUE)))
												.addGroup(
														Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.TRAILING)
																				.addComponent(
																						roomAddButton,
																						GroupLayout.PREFERRED_SIZE,
																						66,
																						GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										roomRoomTypeLabel,
																										GroupLayout.DEFAULT_SIZE,
																										139,
																										Short.MAX_VALUE)
																								.addPreferredGap(
																										ComponentPlacement.RELATED)
																								.addComponent(
																										roomNoLst,
																										GroupLayout.PREFERRED_SIZE,
																										120,
																										GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(
																		ComponentPlacement.RELATED)))
								.addGap(34)));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(22)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														roomDormNumberLabel)
												.addComponent(
														cboxDorm,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addGap(21)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														roomRoomNumberLabel)
												.addComponent(
														cboxRoomType,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.RELATED,
										22, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addComponent(roomRoomTypeLabel)
												.addComponent(
														roomNoLst,
														GroupLayout.PREFERRED_SIZE,
														22,
														GroupLayout.PREFERRED_SIZE))
								.addGap(28).addComponent(roomAddButton)
								.addGap(45)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void fillCBoxRoomType() {
		DBConnection conn = new DBConnection();
		ArrayList<Integer> list;
		try {
			list = conn.displayRoomType();
			for (int i = 0; i < list.size(); i++)
				cboxRoomType.addItem(list.get(i));
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	private void displayRoomTypeAction(ActionEvent evt) {
		iscBoxRoomClicked = true;
		System.out.println("Selected Room: " + cboxRoomType.getSelectedItem().toString());
	}

	private void fillCBoxDorm() {
		DBConnection conn = new DBConnection();
		ArrayList<String> list = null;
		try {
			list = conn.displayDorm();
			for (int i = 0; i < list.size(); i++)
				cboxDorm.addItem(list.get(i));
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void displayDormBoxAction(ActionEvent evt) {
		System.out.println("click");
		System.out.println(cboxDorm.getSelectedItem().toString());
		if (cboxDorm.getSelectedItem().toString().equals("Dorm 1")) {
			System.out.println(cboxDorm.getSelectedItem().toString());
			generateIdForRooms();
		}
	}

	private void generateIdForRooms() {
		DBConnection conn = new DBConnection();
		AtomicInteger nextId;
		ArrayList<String> roomNoList = new ArrayList<>();
		int id;
		conn.retrieveRoomNo(cboxDorm.getSelectedItem().toString());
		roomNoList = conn.getRoomNoList();
		System.out.println(cboxDorm.getSelectedItem().toString());
		if (cboxDorm.getSelectedItem().toString().equals("Dorm 1")) {
			nextId = new AtomicInteger(100);
			id = nextId.incrementAndGet();
			System.out.println(id);
			while (roomNoList.contains("id")) {
				id = nextId.incrementAndGet();
				System.out.println(id + "bu");
			}

			listModelRoom.addElement(id);
		}
	}

	private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt)
			throws SQLException {
		Room room = new Room();
		if (roomNoLst.getModel().equals(null)) {
			JOptionPane.showMessageDialog(getContentPane(), "No room");
		} else {
			int roomNo = (int) roomNoLst.getModel().getElementAt(0);
			room.setRoomNo(roomNo);
		}

		if (iscBoxRoomClicked) {
			String type = cboxRoomType.getSelectedItem().toString();
			int roomType = Integer.parseInt(type);
			room.setTypeName(roomType);
		} else {
			JOptionPane.showMessageDialog(getContentPane(),
					"Please choose a room type!");
		}

		Dorm dorm = new Dorm();
		if (cboxDorm.getSelectedItem().toString().isEmpty()) {
			JOptionPane.showMessageDialog(getContentPane(),
					"Please choose a dorm!");
		} else {
			String dormName = cboxDorm.getSelectedItem().toString();
			dorm.setDormName(dormName);
		}
		DBConnection connection = new DBConnection();
		if (connection.insertRoom(room, dorm)) {
			JOptionPane.showMessageDialog(getContentPane(),
					"Registration is completed");
			listModelRoom.clear();
		} else {
			JOptionPane.showMessageDialog(getContentPane(),
					"Registration is not completed, try again!");
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton roomAddButton;
	private javax.swing.JButton dormAddDutton;
	private javax.swing.JLabel roomDormNumberLabel;
	private javax.swing.JLabel roomRoomNumberLabel;
	private javax.swing.JLabel roomRoomTypeLabel;
	private JList roomNoLst;
	private DefaultListModel listModelRoom;
	private Boolean iscBoxRoomClicked = false;
}
