package view;

import javax.swing.DefaultListModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ListModel;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.JList;
import javax.swing.JScrollPane;

import database.DBConnection;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTabbedPane;

import java.awt.Color;

import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.MatteBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.border.TitledBorder;
import javax.swing.UIManager;

import org.jdatepicker.impl.UtilDateModel;

import com.toedter.calendar.JCalendar;

import java.awt.Button;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Nazli
 */
public class SearchAllWindow extends javax.swing.JFrame {
	private JTable searchTable;
	private JTextField startDateTextField;
	private JTextField endDateTextField;
	private Button enterButton;

	/**
	 * Creates new form DormWindow
	 */
	public SearchAllWindow() {
		setTitle("Search");
		getContentPane().setLayout(null);
		
		Button endDateButton = new Button("End Date");
		endDateButton.setBounds(191, 10, 70, 22);
		getContentPane().add(endDateButton);
		
		Button startDateButton = new Button("Start Date");
		startDateButton.setBounds(10, 10, 70, 22);
		getContentPane().add(startDateButton);
		
		searchTable = new JTable();
		searchTable.setColumnSelectionAllowed(true);
		searchTable.setBounds(10, 52, 462, 237);
		getContentPane().add(searchTable);
		
		startDateTextField = new JTextField();
		startDateTextField.setBounds(86, 10, 86, 20);
		getContentPane().add(startDateTextField);
		startDateTextField.setColumns(10);
		
		endDateTextField = new JTextField();
		endDateTextField.setBounds(267, 10, 86, 20);
		getContentPane().add(endDateTextField);
		endDateTextField.setColumns(10);
		
		enterButton = new Button("ENTER");
		enterButton.setFont(new Font("Tahoma", Font.BOLD, 12));
		enterButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		enterButton.setBounds(392, 10, 80, 22);
		getContentPane().add(enterButton);
		
		startDateButton.addActionListener(new ActionListener() {
			StartDatePopup startDatePopup = new StartDatePopup();
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				startDatePopup.setVisible(true);
			}
		});
		
		endDateButton.addActionListener(new ActionListener() {
			EndDatePopup endDatePopup = new EndDatePopup();
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				endDatePopup.setVisible(true);
			}
		});
		
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

	}
}
